// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

void deleteoption(lv_event_t * e)
{
	// Your code here
}

void addoption(lv_event_t * e)
{
	// Your code here
}

void doRescale(lv_event_t * e)
{
	// Your code here
}

void doTareit(lv_event_t * e)
{
	// Your code here
}

void doSaveme(lv_event_t * e)
{
	// Your code here
}

void takeSample(lv_event_t * e)
{
	// Your code here
}
