// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void deleteoption(lv_event_t * e);
void addoption(lv_event_t * e);
void doRescale(lv_event_t * e);
void doTareit(lv_event_t * e);
void doSaveme(lv_event_t * e);
void takeSample(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
