// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Main2 = NULL;
lv_obj_t * ui_time1 = NULL;
lv_obj_t * ui_battery1 = NULL;
lv_obj_t * ui_wifiSignal1 = NULL;
lv_obj_t * ui_setting1 = NULL;
lv_obj_t * ui_rescale = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_tare = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_Panel2 = NULL;
lv_obj_t * ui_Panel3 = NULL;
lv_obj_t * ui_Label12 = NULL;
lv_obj_t * ui_Label20 = NULL;
lv_obj_t * ui_Panel5 = NULL;
lv_obj_t * ui_Label22 = NULL;
lv_obj_t * ui_Label21 = NULL;
lv_obj_t * ui_Panel6 = NULL;
lv_obj_t * ui_Label24 = NULL;
lv_obj_t * ui_Label23 = NULL;
lv_obj_t * ui_Dropdown2 = NULL;
lv_obj_t * ui_itemName = NULL;
lv_obj_t * ui_save = NULL;
lv_obj_t * ui_Label27 = NULL;
lv_obj_t * ui_keyBoName = NULL;
lv_obj_t * ui_back2 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_Button5 = NULL;
lv_obj_t * ui_Label3 = NULL;
// event funtions
void ui_event_rescale(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        doRescale(e);
    }
}

void ui_event_tare(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        doTareit(e);
    }
}

void ui_event_itemName(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_keyBoName,  ui_itemName);
        _ui_flag_modify(ui_keyBoName, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_save(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        doSaveme(e);
    }
}

void ui_event_keyBoName(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CANCEL) {
        _ui_flag_modify(ui_keyBoName, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
    if(event_code == LV_EVENT_READY) {
        _ui_flag_modify(ui_keyBoName, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_back2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Main, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Main_screen_init);
    }
}

void ui_event_Button5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        takeSample(e);
    }
}

// build funtions

void ui_Main2_screen_init(void)
{
    ui_Main2 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Main2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_time1 = lv_label_create(ui_Main2);
    lv_obj_set_width(ui_time1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_time1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_time1, -210);
    lv_obj_set_y(ui_time1, -114);
    lv_obj_set_align(ui_time1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_time1, "Time: ");

    ui_battery1 = lv_image_create(ui_Main2);
    lv_image_set_src(ui_battery1, &ui_img_batt_batt_0_png);
    lv_obj_set_width(ui_battery1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_battery1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_battery1, 211);
    lv_obj_set_y(ui_battery1, -112);
    lv_obj_set_align(ui_battery1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_battery1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_battery1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_battery1, 150);

    ui_wifiSignal1 = lv_image_create(ui_Main2);
    lv_image_set_src(ui_wifiSignal1, &ui_img_wifi_wifi_0_png);
    lv_obj_set_width(ui_wifiSignal1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wifiSignal1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wifiSignal1, 163);
    lv_obj_set_y(ui_wifiSignal1, -112);
    lv_obj_set_align(ui_wifiSignal1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wifiSignal1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_wifiSignal1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_wifiSignal1, 150);

    ui_setting1 = lv_imagebutton_create(ui_Main2);
    lv_imagebutton_set_src(ui_setting1, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_setting_setting2_png, NULL);
    lv_obj_set_height(ui_setting1, 31);
    lv_obj_set_width(ui_setting1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_setting1, 118);
    lv_obj_set_y(ui_setting1, -113);
    lv_obj_set_align(ui_setting1, LV_ALIGN_CENTER);

    ui_rescale = lv_button_create(ui_Main2);
    lv_obj_set_width(ui_rescale, 100);
    lv_obj_set_height(ui_rescale, 50);
    lv_obj_set_x(ui_rescale, 165);
    lv_obj_set_y(ui_rescale, -15);
    lv_obj_set_align(ui_rescale, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_rescale, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_rescale, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_rescale);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Rescale");

    ui_tare = lv_button_create(ui_Main2);
    lv_obj_set_width(ui_tare, 100);
    lv_obj_set_height(ui_tare, 50);
    lv_obj_set_x(ui_tare, 165);
    lv_obj_set_y(ui_tare, 43);
    lv_obj_set_align(ui_tare, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_tare, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_tare, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label4 = lv_label_create(ui_tare);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Tare");

    ui_Panel2 = lv_obj_create(ui_Main2);
    lv_obj_set_width(ui_Panel2, 331);
    lv_obj_set_height(ui_Panel2, 225);
    lv_obj_set_x(ui_Panel2, -67);
    lv_obj_set_y(ui_Panel2, 19);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel3 = lv_obj_create(ui_Main2);
    lv_obj_set_width(ui_Panel3, 100);
    lv_obj_set_height(ui_Panel3, 69);
    lv_obj_set_x(ui_Panel3, -150);
    lv_obj_set_y(ui_Panel3, 3);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label12 = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, 0);
    lv_obj_set_y(ui_Label12, -14);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "Weight");

    ui_Label20 = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label20, -1);
    lv_obj_set_y(ui_Label20, 10);
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "0");

    ui_Panel5 = lv_obj_create(ui_Main2);
    lv_obj_set_width(ui_Panel5, 100);
    lv_obj_set_height(ui_Panel5, 60);
    lv_obj_set_align(ui_Panel5, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label22 = lv_label_create(ui_Panel5);
    lv_obj_set_width(ui_Label22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label22, 0);
    lv_obj_set_y(ui_Label22, 14);
    lv_obj_set_align(ui_Label22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label22, "0");

    ui_Label21 = lv_label_create(ui_Panel5);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label21, 0);
    lv_obj_set_y(ui_Label21, -10);
    lv_obj_set_align(ui_Label21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label21, "Unit Weight");

    ui_Panel6 = lv_obj_create(ui_Main2);
    lv_obj_set_width(ui_Panel6, 100);
    lv_obj_set_height(ui_Panel6, 60);
    lv_obj_set_x(ui_Panel6, 0);
    lv_obj_set_y(ui_Panel6, 85);
    lv_obj_set_align(ui_Panel6, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label24 = lv_label_create(ui_Panel6);
    lv_obj_set_width(ui_Label24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label24, 0);
    lv_obj_set_y(ui_Label24, -7);
    lv_obj_set_align(ui_Label24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label24, "Quantity");

    ui_Label23 = lv_label_create(ui_Panel6);
    lv_obj_set_width(ui_Label23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label23, 0);
    lv_obj_set_y(ui_Label23, 14);
    lv_obj_set_align(ui_Label23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label23, "0");

    ui_Dropdown2 = lv_dropdown_create(ui_Main2);
    lv_dropdown_set_options(ui_Dropdown2, "PCS\nKg\ng\nml\nlbs");
    lv_obj_set_width(ui_Dropdown2, 115);
    lv_obj_set_height(ui_Dropdown2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dropdown2, 170);
    lv_obj_set_y(ui_Dropdown2, -71);
    lv_obj_set_align(ui_Dropdown2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_itemName = lv_textarea_create(ui_Main2);
    lv_obj_set_width(ui_itemName, 300);
    lv_obj_set_height(ui_itemName, 40);
    lv_obj_set_x(ui_itemName, -60);
    lv_obj_set_y(ui_itemName, -60);
    lv_obj_set_align(ui_itemName, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_itemName, "Placeholder...");

    ui_save = lv_button_create(ui_Main2);
    lv_obj_set_width(ui_save, 100);
    lv_obj_set_height(ui_save, 50);
    lv_obj_set_x(ui_save, 165);
    lv_obj_set_y(ui_save, 100);
    lv_obj_set_align(ui_save, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_save, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_save, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label27 = lv_label_create(ui_save);
    lv_obj_set_width(ui_Label27, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label27, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label27, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label27, "Save");

    ui_keyBoName = lv_keyboard_create(ui_Main2);
    lv_obj_set_width(ui_keyBoName, 460);
    lv_obj_set_height(ui_keyBoName, 140);
    lv_obj_set_x(ui_keyBoName, 0);
    lv_obj_set_y(ui_keyBoName, 60);
    lv_obj_set_align(ui_keyBoName, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_keyBoName, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_back2 = lv_button_create(ui_Main2);
    lv_obj_set_width(ui_back2, 46);
    lv_obj_set_height(ui_back2, 35);
    lv_obj_set_x(ui_back2, -2);
    lv_obj_set_y(ui_back2, -113);
    lv_obj_set_align(ui_back2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_back2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_back2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_back2);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "<");

    ui_Button5 = lv_button_create(ui_Main2);
    lv_obj_set_width(ui_Button5, 100);
    lv_obj_set_height(ui_Button5, 50);
    lv_obj_set_x(ui_Button5, -150);
    lv_obj_set_y(ui_Button5, 84);
    lv_obj_set_align(ui_Button5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label3 = lv_label_create(ui_Button5);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Sample");

    lv_obj_add_event_cb(ui_rescale, ui_event_rescale, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_tare, ui_event_tare, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_itemName, ui_event_itemName, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_save, ui_event_save, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_keyBoName, ui_itemName);
    lv_obj_add_event_cb(ui_keyBoName, ui_event_keyBoName, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_back2, ui_event_back2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button5, ui_event_Button5, LV_EVENT_ALL, NULL);

}

void ui_Main2_screen_destroy(void)
{
    if(ui_Main2) lv_obj_del(ui_Main2);

    // NULL screen variables
    ui_Main2 = NULL;
    ui_time1 = NULL;
    ui_battery1 = NULL;
    ui_wifiSignal1 = NULL;
    ui_setting1 = NULL;
    ui_rescale = NULL;
    ui_Label1 = NULL;
    ui_tare = NULL;
    ui_Label4 = NULL;
    ui_Panel2 = NULL;
    ui_Panel3 = NULL;
    ui_Label12 = NULL;
    ui_Label20 = NULL;
    ui_Panel5 = NULL;
    ui_Label22 = NULL;
    ui_Label21 = NULL;
    ui_Panel6 = NULL;
    ui_Label24 = NULL;
    ui_Label23 = NULL;
    ui_Dropdown2 = NULL;
    ui_itemName = NULL;
    ui_save = NULL;
    ui_Label27 = NULL;
    ui_keyBoName = NULL;
    ui_back2 = NULL;
    ui_Label2 = NULL;
    ui_Button5 = NULL;
    ui_Label3 = NULL;

}
