// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef UI_MAIN_H
#define UI_MAIN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Main
extern void ui_Main_screen_init(void);
extern void ui_Main_screen_destroy(void);
extern lv_obj_t * ui_Main;
extern lv_obj_t * ui_time;
extern lv_obj_t * ui_battery;
extern lv_obj_t * ui_wifiSignal;
extern void ui_event_setting(lv_event_t * e);
extern lv_obj_t * ui_setting;
extern lv_obj_t * ui_Button16;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Button17;
extern lv_obj_t * ui_Label15;
extern void ui_event_add(lv_event_t * e);
extern lv_obj_t * ui_add;
extern lv_obj_t * ui_Label16;
extern void ui_event_delete(lv_event_t * e);
extern lv_obj_t * ui_delete;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Panel8;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Panel9;
extern lv_obj_t * ui_Label25;
extern void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern void ui_event_Label26(lv_event_t * e);
extern lv_obj_t * ui_Label26;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

