// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef UI_MAIN2_H
#define UI_MAIN2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Main2
extern void ui_Main2_screen_init(void);
extern void ui_Main2_screen_destroy(void);
extern lv_obj_t * ui_Main2;
extern lv_obj_t * ui_time1;
extern lv_obj_t * ui_battery1;
extern lv_obj_t * ui_wifiSignal1;
extern lv_obj_t * ui_setting1;
extern void ui_event_rescale(lv_event_t * e);
extern lv_obj_t * ui_rescale;
extern lv_obj_t * ui_Label1;
extern void ui_event_tare(lv_event_t * e);
extern lv_obj_t * ui_tare;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_Dropdown2;
extern void ui_event_itemName(lv_event_t * e);
extern lv_obj_t * ui_itemName;
extern void ui_event_save(lv_event_t * e);
extern lv_obj_t * ui_save;
extern lv_obj_t * ui_Label27;
extern void ui_event_keyBoName(lv_event_t * e);
extern lv_obj_t * ui_keyBoName;
extern void ui_event_back2(lv_event_t * e);
extern lv_obj_t * ui_back2;
extern lv_obj_t * ui_Label2;
extern void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Label3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

