// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Main = NULL;
lv_obj_t * ui_time = NULL;
lv_obj_t * ui_battery = NULL;
lv_obj_t * ui_wifiSignal = NULL;
lv_obj_t * ui_setting = NULL;
lv_obj_t * ui_Button16 = NULL;
lv_obj_t * ui_Label14 = NULL;
lv_obj_t * ui_Button17 = NULL;
lv_obj_t * ui_Label15 = NULL;
lv_obj_t * ui_add = NULL;
lv_obj_t * ui_Label16 = NULL;
lv_obj_t * ui_delete = NULL;
lv_obj_t * ui_Label17 = NULL;
lv_obj_t * ui_Label11 = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_Panel8 = NULL;
lv_obj_t * ui_Label13 = NULL;
lv_obj_t * ui_Panel9 = NULL;
lv_obj_t * ui_Label25 = NULL;
lv_obj_t * ui_Button2 = NULL;
lv_obj_t * ui_Label26 = NULL;
// event funtions
void ui_event_setting(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_WifiConfig, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_WifiConfig_screen_init);
    }
}

void ui_event_add(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Main2, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Main2_screen_init);
    }
}

void ui_event_delete(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        deleteoption(e);
    }
}

void ui_event_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        addoption(e);
    }
}

void ui_event_Label26(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        addoption(e);
    }
}

// build funtions

void ui_Main_screen_init(void)
{
    ui_Main = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Main, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_time = lv_label_create(ui_Main);
    lv_obj_set_width(ui_time, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_time, -210);
    lv_obj_set_y(ui_time, -114);
    lv_obj_set_align(ui_time, LV_ALIGN_CENTER);
    lv_label_set_text(ui_time, "Time: ");

    ui_battery = lv_image_create(ui_Main);
    lv_image_set_src(ui_battery, &ui_img_batt_batt_0_png);
    lv_obj_set_width(ui_battery, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_battery, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_battery, 211);
    lv_obj_set_y(ui_battery, -112);
    lv_obj_set_align(ui_battery, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_battery, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_battery, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_battery, 150);

    ui_wifiSignal = lv_image_create(ui_Main);
    lv_image_set_src(ui_wifiSignal, &ui_img_wifi_wifi_0_png);
    lv_obj_set_width(ui_wifiSignal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wifiSignal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wifiSignal, 163);
    lv_obj_set_y(ui_wifiSignal, -112);
    lv_obj_set_align(ui_wifiSignal, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wifiSignal, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_wifiSignal, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_wifiSignal, 150);

    ui_setting = lv_imagebutton_create(ui_Main);
    lv_imagebutton_set_src(ui_setting, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_setting_setting2_png, NULL);
    lv_obj_set_height(ui_setting, 31);
    lv_obj_set_width(ui_setting, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_setting, 118);
    lv_obj_set_y(ui_setting, -114);
    lv_obj_set_align(ui_setting, LV_ALIGN_CENTER);

    ui_Button16 = lv_button_create(ui_Main);
    lv_obj_set_width(ui_Button16, 70);
    lv_obj_set_height(ui_Button16, 50);
    lv_obj_set_x(ui_Button16, 183);
    lv_obj_set_y(ui_Button16, 105);
    lv_obj_set_align(ui_Button16, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button16, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label14 = lv_label_create(ui_Button16);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "Power");

    ui_Button17 = lv_button_create(ui_Main);
    lv_obj_set_width(ui_Button17, 70);
    lv_obj_set_height(ui_Button17, 50);
    lv_obj_set_x(ui_Button17, 93);
    lv_obj_set_y(ui_Button17, 105);
    lv_obj_set_align(ui_Button17, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button17, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label15 = lv_label_create(ui_Button17);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "Sync");

    ui_add = lv_button_create(ui_Main);
    lv_obj_set_width(ui_add, 70);
    lv_obj_set_height(ui_add, 50);
    lv_obj_set_x(ui_add, -192);
    lv_obj_set_y(ui_add, 105);
    lv_obj_set_align(ui_add, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_add, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_add, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label16 = lv_label_create(ui_add);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "Add");

    ui_delete = lv_button_create(ui_Main);
    lv_obj_set_width(ui_delete, 70);
    lv_obj_set_height(ui_delete, 50);
    lv_obj_set_x(ui_delete, -90);
    lv_obj_set_y(ui_delete, 105);
    lv_obj_set_align(ui_delete, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_delete, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_delete, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label17 = lv_label_create(ui_delete);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "Delete");

    ui_Label11 = lv_label_create(ui_Main);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, -10);
    lv_obj_set_y(ui_Label11, -110);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "Main Screen");

    ui_Panel1 = lv_obj_create(ui_Main);
    lv_obj_set_width(ui_Panel1, 460);
    lv_obj_set_height(ui_Panel1, 169);
    lv_obj_set_x(ui_Panel1, 0);
    lv_obj_set_y(ui_Panel1, -13);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel8 = lv_obj_create(ui_Main);
    lv_obj_set_width(ui_Panel8, 70);
    lv_obj_set_height(ui_Panel8, 64);
    lv_obj_set_x(ui_Panel8, 180);
    lv_obj_set_y(ui_Panel8, -55);
    lv_obj_set_align(ui_Panel8, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label13 = lv_label_create(ui_Panel8);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "Item\nCount");

    ui_Panel9 = lv_obj_create(ui_Main);
    lv_obj_set_width(ui_Panel9, 70);
    lv_obj_set_height(ui_Panel9, 66);
    lv_obj_set_x(ui_Panel9, 179);
    lv_obj_set_y(ui_Panel9, 28);
    lv_obj_set_align(ui_Panel9, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label25 = lv_label_create(ui_Panel9);
    lv_obj_set_width(ui_Label25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label25, "Weight");

    ui_Button2 = lv_button_create(ui_Main);
    lv_obj_set_width(ui_Button2, 70);
    lv_obj_set_height(ui_Button2, 50);
    lv_obj_set_x(ui_Button2, 0);
    lv_obj_set_y(ui_Button2, 105);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label26 = lv_label_create(ui_Button2);
    lv_obj_set_width(ui_Label26, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label26, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label26, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label26, "Config");

    lv_obj_add_event_cb(ui_setting, ui_event_setting, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_add, ui_event_add, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_delete, ui_event_delete, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Label26, ui_event_Label26, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);

}

void ui_Main_screen_destroy(void)
{
    if(ui_Main) lv_obj_del(ui_Main);

    // NULL screen variables
    ui_Main = NULL;
    ui_time = NULL;
    ui_battery = NULL;
    ui_wifiSignal = NULL;
    ui_setting = NULL;
    ui_Button16 = NULL;
    ui_Label14 = NULL;
    ui_Button17 = NULL;
    ui_Label15 = NULL;
    ui_add = NULL;
    ui_Label16 = NULL;
    ui_delete = NULL;
    ui_Label17 = NULL;
    ui_Label11 = NULL;
    ui_Panel1 = NULL;
    ui_Panel8 = NULL;
    ui_Label13 = NULL;
    ui_Panel9 = NULL;
    ui_Label25 = NULL;
    ui_Button2 = NULL;
    ui_Label26 = NULL;

}
