// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_WifiConfig = NULL;
lv_obj_t * ui_HeadPanel = NULL;
lv_obj_t * ui_backWi = NULL;
lv_obj_t * ui_Label18 = NULL;
lv_obj_t * ui_Label19 = NULL;
lv_obj_t * ui_wifiSw = NULL;
lv_obj_t * ui_wifiList = NULL;
lv_obj_t * ui_KeyboardWifi = NULL;
lv_obj_t * ui_EnterPasswordPanel = NULL;
lv_obj_t * ui_EnterPassText = NULL;
lv_obj_t * ui_wiPassword = NULL;
lv_obj_t * ui_Loading = NULL;
lv_obj_t * ui_loadPara = NULL;
lv_obj_t * ui_loadHead = NULL;
lv_obj_t * ui_loadOk = NULL;
lv_obj_t * ui_Label10 = NULL;
// event funtions
void ui_event_backWi(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Main, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Main_screen_init);
    }
}

void ui_event_wifiSw(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_flag_modify(ui_wifiList, LV_OBJ_FLAG_CLICKABLE, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_wifiList(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_flag_modify(ui_EnterPasswordPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_KeyboardWifi, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_state_modify(ui_wiPassword, LV_STATE_FOCUSED, _UI_MODIFY_STATE_ADD);
    }
}

void ui_event_KeyboardWifi(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CANCEL) {
        _ui_flag_modify(ui_KeyboardWifi, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_EnterPasswordPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
    if(event_code == LV_EVENT_READY) {
        _ui_flag_modify(ui_EnterPasswordPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_KeyboardWifi, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_wiPassword(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_KeyboardWifi, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_EnterPasswordPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_loadOk(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_loadOk, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_Loading, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_backWi, LV_OBJ_FLAG_CLICKABLE, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_wifiSw, LV_OBJ_FLAG_CLICKABLE, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_wifiList, LV_OBJ_FLAG_CLICKABLE, _UI_MODIFY_FLAG_ADD);
    }
}

// build funtions

void ui_WifiConfig_screen_init(void)
{
    ui_WifiConfig = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_WifiConfig, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HeadPanel = lv_obj_create(ui_WifiConfig);
    lv_obj_set_width(ui_HeadPanel, 465);
    lv_obj_set_height(ui_HeadPanel, 59);
    lv_obj_set_x(ui_HeadPanel, 0);
    lv_obj_set_y(ui_HeadPanel, -100);
    lv_obj_set_align(ui_HeadPanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_HeadPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_backWi = lv_button_create(ui_HeadPanel);
    lv_obj_set_width(ui_backWi, 50);
    lv_obj_set_height(ui_backWi, 48);
    lv_obj_set_x(ui_backWi, -199);
    lv_obj_set_y(ui_backWi, 0);
    lv_obj_set_align(ui_backWi, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_backWi, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_backWi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label18 = lv_label_create(ui_backWi);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "<");

    ui_Label19 = lv_label_create(ui_HeadPanel);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "WiFi-Configuration");

    ui_wifiSw = lv_switch_create(ui_HeadPanel);
    lv_obj_set_width(ui_wifiSw, 62);
    lv_obj_set_height(ui_wifiSw, 31);
    lv_obj_set_x(ui_wifiSw, 180);
    lv_obj_set_y(ui_wifiSw, -1);
    lv_obj_set_align(ui_wifiSw, LV_ALIGN_CENTER);

    ui_wifiList = lv_dropdown_create(ui_WifiConfig);
    lv_dropdown_set_options(ui_wifiList, "option1\noption2\noption3");
    lv_dropdown_set_text(ui_wifiList, "WiFi Scan Disabled");
    lv_obj_set_width(ui_wifiList, 400);
    lv_obj_set_height(ui_wifiList, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wifiList, 0);
    lv_obj_set_y(ui_wifiList, -36);
    lv_obj_set_align(ui_wifiList, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wifiList, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_wifiList, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_KeyboardWifi = lv_keyboard_create(ui_WifiConfig);
    lv_obj_set_width(ui_KeyboardWifi, 460);
    lv_obj_set_height(ui_KeyboardWifi, 140);
    lv_obj_set_x(ui_KeyboardWifi, 0);
    lv_obj_set_y(ui_KeyboardWifi, 60);
    lv_obj_set_align(ui_KeyboardWifi, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_KeyboardWifi, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_EnterPasswordPanel = lv_obj_create(ui_WifiConfig);
    lv_obj_set_width(ui_EnterPasswordPanel, 449);
    lv_obj_set_height(ui_EnterPasswordPanel, 109);
    lv_obj_set_x(ui_EnterPasswordPanel, 0);
    lv_obj_set_y(ui_EnterPasswordPanel, -70);
    lv_obj_set_align(ui_EnterPasswordPanel, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_EnterPasswordPanel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_EnterPasswordPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_EnterPassText = lv_label_create(ui_EnterPasswordPanel);
    lv_obj_set_width(ui_EnterPassText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_EnterPassText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_EnterPassText, 0);
    lv_obj_set_y(ui_EnterPassText, -19);
    lv_obj_set_align(ui_EnterPassText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_EnterPassText, "Please Enter Password Here: ");

    ui_wiPassword = lv_textarea_create(ui_EnterPasswordPanel);
    lv_obj_set_width(ui_wiPassword, 317);
    lv_obj_set_height(ui_wiPassword, 42);
    lv_obj_set_x(ui_wiPassword, -6);
    lv_obj_set_y(ui_wiPassword, 22);
    lv_obj_set_align(ui_wiPassword, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_wiPassword, "Enter Password");
    lv_textarea_set_one_line(ui_wiPassword, true);
    lv_textarea_set_password_mode(ui_wiPassword, true);

    ui_Loading = lv_obj_create(ui_WifiConfig);
    lv_obj_set_width(ui_Loading, 334);
    lv_obj_set_height(ui_Loading, 157);
    lv_obj_set_x(ui_Loading, 0);
    lv_obj_set_y(ui_Loading, -25);
    lv_obj_set_align(ui_Loading, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Loading, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_Loading, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_loadPara = lv_label_create(ui_Loading);
    lv_obj_set_width(ui_loadPara, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_loadPara, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_loadPara, 0);
    lv_obj_set_y(ui_loadPara, -12);
    lv_obj_set_align(ui_loadPara, LV_ALIGN_CENTER);
    lv_label_set_text(ui_loadPara, "Please Wait\nAttempting to connect WiFi");
    lv_obj_set_style_text_align(ui_loadPara, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_loadHead = lv_label_create(ui_Loading);
    lv_obj_set_width(ui_loadHead, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_loadHead, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_loadHead, 0);
    lv_obj_set_y(ui_loadHead, -53);
    lv_obj_set_align(ui_loadHead, LV_ALIGN_CENTER);
    lv_label_set_text(ui_loadHead, "WiFi Alerts");

    ui_loadOk = lv_button_create(ui_Loading);
    lv_obj_set_width(ui_loadOk, 77);
    lv_obj_set_height(ui_loadOk, 48);
    lv_obj_set_x(ui_loadOk, 0);
    lv_obj_set_y(ui_loadOk, 44);
    lv_obj_set_align(ui_loadOk, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_loadOk, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_loadOk, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label10 = lv_label_create(ui_loadOk);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "Ok");

    lv_obj_add_event_cb(ui_backWi, ui_event_backWi, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_wifiSw, ui_event_wifiSw, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_wifiList, ui_event_wifiList, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_KeyboardWifi, ui_wiPassword);
    lv_obj_add_event_cb(ui_KeyboardWifi, ui_event_KeyboardWifi, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_wiPassword, ui_event_wiPassword, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_loadOk, ui_event_loadOk, LV_EVENT_ALL, NULL);

}

void ui_WifiConfig_screen_destroy(void)
{
    if(ui_WifiConfig) lv_obj_del(ui_WifiConfig);

    // NULL screen variables
    ui_WifiConfig = NULL;
    ui_HeadPanel = NULL;
    ui_backWi = NULL;
    ui_Label18 = NULL;
    ui_Label19 = NULL;
    ui_wifiSw = NULL;
    ui_wifiList = NULL;
    ui_KeyboardWifi = NULL;
    ui_EnterPasswordPanel = NULL;
    ui_EnterPassText = NULL;
    ui_wiPassword = NULL;
    ui_Loading = NULL;
    ui_loadPara = NULL;
    ui_loadHead = NULL;
    ui_loadOk = NULL;
    ui_Label10 = NULL;

}
