// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef UI_WIFICONFIG_H
#define UI_WIFICONFIG_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_WifiConfig
extern void ui_WifiConfig_screen_init(void);
extern void ui_WifiConfig_screen_destroy(void);
extern lv_obj_t * ui_WifiConfig;
extern lv_obj_t * ui_HeadPanel;
extern void ui_event_backWi(lv_event_t * e);
extern lv_obj_t * ui_backWi;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Label19;
extern void ui_event_wifiSw(lv_event_t * e);
extern lv_obj_t * ui_wifiSw;
extern void ui_event_wifiList(lv_event_t * e);
extern lv_obj_t * ui_wifiList;
extern void ui_event_KeyboardWifi(lv_event_t * e);
extern lv_obj_t * ui_KeyboardWifi;
extern lv_obj_t * ui_EnterPasswordPanel;
extern lv_obj_t * ui_EnterPassText;
extern void ui_event_wiPassword(lv_event_t * e);
extern lv_obj_t * ui_wiPassword;
extern lv_obj_t * ui_Loading;
extern lv_obj_t * ui_loadPara;
extern lv_obj_t * ui_loadHead;
extern void ui_event_loadOk(lv_event_t * e);
extern lv_obj_t * ui_loadOk;
extern lv_obj_t * ui_Label10;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

